/*
 * JSP generated by Resin-3.0.22 (built Mon, 13 Nov 2006 09:32:38 PST)
 */

package _jsp._web_22dinf._v2;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;

public class _portal__jsp extends com.caucho.jsp.JavaPage{
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.Application _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = com.caucho.jsp.QJspFactory.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html; charset=utf-8");
    request.setCharacterEncoding("UTF-8");
    com.caucho.jstl.el.FormatNumberTag _jsp_FormatNumberTag_0 = null;
    com.caucho.jstl.el.FormatDateTag _jsp_FormatDateTag_1 = null;
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
      _caucho_expr_0.print(out, pageContext, false);
      out.write(_jsp_string1, 0, _jsp_string1.length);
      pageContext.requestSetOrRemove("base", _caucho_expr_1.evalObject(pageContext));
      out.write(_jsp_string2, 0, _jsp_string2.length);
      pageContext.sessionSetOrRemove("lang", "i18n/Page");
      out.write(_jsp_string2, 0, _jsp_string2.length);
      pageContext.sessionSetOrRemove("bundle", "i18n/Credit_card");
      out.write(_jsp_string3, 0, _jsp_string3.length);
      _caucho_expr_2.print(out, pageContext, false);
      out.write(_jsp_string4, 0, _jsp_string4.length);
      _caucho_expr_3.print(out, pageContext, false);
      out.write(' ');
      _caucho_expr_4.print(out, pageContext, false);
      out.write(_jsp_string5, 0, _jsp_string5.length);
      if (_jsp_FormatNumberTag_0 == null) {
        _jsp_FormatNumberTag_0 = new com.caucho.jstl.el.FormatNumberTag();
        _jsp_FormatNumberTag_0.setPageContext(pageContext);
        _jsp_FormatNumberTag_0.setParent((javax.servlet.jsp.tagext.Tag) null);
        _jsp_FormatNumberTag_0.setPattern(_caucho_expr_5);
      }

      _jsp_FormatNumberTag_0.setValue(_caucho_expr_6);
      _jsp_FormatNumberTag_0.doEndTag();
      out.write(_jsp_string6, 0, _jsp_string6.length);
      _caucho_expr_7.print(out, pageContext, false);
      out.write(_jsp_string7, 0, _jsp_string7.length);
      _caucho_expr_2.print(out, pageContext, false);
      out.write('(');
      _caucho_expr_8.print(out, pageContext, false);
      out.write(_jsp_string8, 0, _jsp_string8.length);
      _caucho_expr_9.print(out, pageContext, false);
      out.write(_jsp_string9, 0, _jsp_string9.length);
      _caucho_expr_10.print(out, pageContext, false);
      out.write(_jsp_string10, 0, _jsp_string10.length);
      _jsp_FormatNumberTag_0.setValue(_caucho_expr_6);
      _jsp_FormatNumberTag_0.doEndTag();
      out.write(_jsp_string11, 0, _jsp_string11.length);
      if (_jsp_FormatDateTag_1 == null) {
        _jsp_FormatDateTag_1 = new com.caucho.jstl.el.FormatDateTag();
        _jsp_FormatDateTag_1.setPageContext(pageContext);
        _jsp_FormatDateTag_1.setParent((javax.servlet.jsp.tagext.Tag) null);
        _jsp_FormatDateTag_1.setType(_caucho_expr_11);
      }

      _jsp_FormatDateTag_1.setValue(_caucho_expr_12);
      _jsp_FormatDateTag_1.doEndTag();
      out.write(_jsp_string12, 0, _jsp_string12.length);
      _caucho_expr_13.print(out, pageContext, false);
      out.write(_jsp_string13, 0, _jsp_string13.length);
      _caucho_expr_14.print(out, pageContext, false);
      out.write(_jsp_string14, 0, _jsp_string14.length);
      _caucho_expr_15.print(out, pageContext, false);
      out.write(_jsp_string15, 0, _jsp_string15.length);
      _caucho_expr_13.print(out, pageContext, false);
      out.write(_jsp_string13, 0, _jsp_string13.length);
      _caucho_expr_14.print(out, pageContext, false);
      out.write(_jsp_string16, 0, _jsp_string16.length);
      _caucho_expr_16.print(out, pageContext, false);
      out.write(_jsp_string17, 0, _jsp_string17.length);
      java.util.Date now;
      now = (java.util.Date) pageContext.getAttribute("now");
      if (now == null) {
        now = new java.util.Date();
        pageContext.setAttribute("now", now);
      }
      out.write(_jsp_string18, 0, _jsp_string18.length);
      _jsp_FormatDateTag_1.setValue(_caucho_expr_17);
      _jsp_FormatDateTag_1.doEndTag();
      out.write(_jsp_string19, 0, _jsp_string19.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      if (_jsp_FormatNumberTag_0 != null)
        _jsp_FormatNumberTag_0.release();
      if (_jsp_FormatDateTag_1 != null)
        _jsp_FormatDateTag_1.release();
      com.caucho.jsp.QJspFactory.freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.make.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.util.CauchoSystem.getVersionId() != -3988812337524854005L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.make.Dependency depend;
      depend = (com.caucho.make.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("WEB-INF/v2/portal.jsp"), 5598764691618645745L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("common/style.jsp"), 5025591737830600425L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("common/tags.jsp"), -4275648674232483211L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("common/head.jsp"), -7797974965276526561L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("common/tail.jsp"), 6812337794366760204L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    depend = new com.caucho.vfs.Depend(mergePath.lookup("C:/Home/Resin/resin-3.0.22/lib/resin.jar"), 8088847092149864614L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, new com.caucho.make.ClassDependency(com.caucho.jstl.el.FormatNumberTag.class, 1295192485790377401L));
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, new com.caucho.make.ClassDependency(com.caucho.jstl.el.FormatDateTag.class, 1354023731864347364L));
  }
  private final static com.caucho.el.Expr _caucho_expr_0 =
    new com.caucho.el.IdExpr("base");
  private final static com.caucho.el.Expr _caucho_expr_1 =
    new com.caucho.el.InterpolateExpr(new com.caucho.el.InterpolateExpr(new com.caucho.el.InterpolateExpr(new com.caucho.el.InterpolateExpr(new com.caucho.el.InterpolateExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.ArrayExpr(new com.caucho.jsp.el.ImplicitObjectExpr("pageContext"), new com.caucho.el.StringLiteral("request")), new com.caucho.el.StringLiteral("scheme")), new com.caucho.el.StringLiteral("://")), new com.caucho.el.ArrayExpr(new com.caucho.el.ArrayExpr(new com.caucho.jsp.el.ImplicitObjectExpr("pageContext"), new com.caucho.el.StringLiteral("request")), new com.caucho.el.StringLiteral("serverName"))), new com.caucho.el.StringLiteral(":")), new com.caucho.el.ArrayExpr(new com.caucho.el.ArrayExpr(new com.caucho.jsp.el.ImplicitObjectExpr("pageContext"), new com.caucho.el.StringLiteral("request")), new com.caucho.el.StringLiteral("serverPort"))), new com.caucho.el.ArrayExpr(new com.caucho.el.ArrayExpr(new com.caucho.jsp.el.ImplicitObjectExpr("pageContext"), new com.caucho.el.StringLiteral("request")), new com.caucho.el.StringLiteral("contextPath")));
  private final static com.caucho.el.Expr _caucho_expr_2 =
    new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("m"), new com.caucho.el.StringLiteral("_sorder")), new com.caucho.el.StringLiteral("subject")), "m._sorder.subject");
  private final static com.caucho.el.Expr _caucho_expr_3 =
    new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("m"), new com.caucho.el.StringLiteral("_sorder")), new com.caucho.el.StringLiteral("seller_name")), "m._sorder.seller_name");
  private final static com.caucho.el.Expr _caucho_expr_4 =
    new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("m"), new com.caucho.el.StringLiteral("_sorder")), new com.caucho.el.StringLiteral("seller_remarks")), "m._sorder.seller_remarks");
  private final static com.caucho.el.Expr _caucho_expr_5 =
    new com.caucho.el.StringLiteral("0.00");
  private final static com.caucho.el.Expr _caucho_expr_6 =
    new com.caucho.el.BinaryExpr(4, new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("m"), new com.caucho.el.StringLiteral("_sorder")), new com.caucho.el.StringLiteral("amount")), "m._sorder.amount"), new com.caucho.el.LongLiteral(100L));
  private final static com.caucho.el.Expr _caucho_expr_7 =
    new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("m"), new com.caucho.el.StringLiteral("_sorder")), new com.caucho.el.StringLiteral("id")), "m._sorder.id");
  private final static com.caucho.el.Expr _caucho_expr_8 =
    new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("m"), new com.caucho.el.StringLiteral("_sorder")), new com.caucho.el.StringLiteral("quantity")), "m._sorder.quantity");
  private final static com.caucho.el.Expr _caucho_expr_9 =
    new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("m"), new com.caucho.el.StringLiteral("_sorder")), new com.caucho.el.StringLiteral("ordernum")), "m._sorder.ordernum");
  private final static com.caucho.el.Expr _caucho_expr_10 =
    new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("m"), new com.caucho.el.StringLiteral("_sorder")), new com.caucho.el.StringLiteral("bodys")), "m._sorder.bodys");
  private final static com.caucho.el.Expr _caucho_expr_11 =
    new com.caucho.el.StringLiteral("both");
  private final static com.caucho.el.Expr _caucho_expr_12 =
    new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("m"), new com.caucho.el.StringLiteral("_sorder")), new com.caucho.el.StringLiteral("createdate")), "m._sorder.createdate");
  private final static com.caucho.el.Expr _caucho_expr_13 =
    new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("m"), new com.caucho.el.StringLiteral("_token")), "m._token");
  private final static com.caucho.el.Expr _caucho_expr_14 =
    new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("m"), new com.caucho.el.StringLiteral("_persistence")), "m._persistence");
  private final static com.caucho.el.Expr _caucho_expr_15 =
    new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("m"), new com.caucho.el.StringLiteral("LEFT_RESP_MSG")), "m.LEFT_RESP_MSG");
  private final static com.caucho.el.Expr _caucho_expr_16 =
    new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("m"), new com.caucho.el.StringLiteral("RIGHT_RESP_MSG")), "m.RIGHT_RESP_MSG");
  private final static com.caucho.el.Expr _caucho_expr_17 =
    new com.caucho.el.IdExpr("now");

  private final static char []_jsp_string15;
  private final static char []_jsp_string1;
  private final static char []_jsp_string4;
  private final static char []_jsp_string19;
  private final static char []_jsp_string16;
  private final static char []_jsp_string6;
  private final static char []_jsp_string3;
  private final static char []_jsp_string5;
  private final static char []_jsp_string7;
  private final static char []_jsp_string18;
  private final static char []_jsp_string13;
  private final static char []_jsp_string10;
  private final static char []_jsp_string2;
  private final static char []_jsp_string14;
  private final static char []_jsp_string11;
  private final static char []_jsp_string8;
  private final static char []_jsp_string12;
  private final static char []_jsp_string0;
  private final static char []_jsp_string17;
  private final static char []_jsp_string9;
  static {
    _jsp_string15 = "</font></label>\n<span class=\"next_anniu\" style=\"margin-left:200px;\"><a href=\"javascript:document.forms[0].submit();\">\u4e0b\u4e00\u6b65</a></span>\n</div>\n\n</div>\n</form>\n<div class=\"sty_lbt\" style=\"margin-bottom:60px; margin-left:3px;\">\n\n<h1>\u6211\u6ca1\u6709\u6613\u751f\u652f\u4ed8\u8d26\u6237\uff0c\u4e5f\u80fd\u4ed8\u6b3e:</h1>\n\n<h2>\u6613\u751f\u652f\u4ed8\u652f\u6301\u56fd\u5185\u4e8c\u5341\u591a\u5bb6\u4e3b\u6d41\u94f6\u884c\u4e0e\u673a\u6784\u7684\u50a8\u84c4\u5361\u3001\u4fe1\u7528\u5361\u7684\u7f51\u4e0a\u4ed8\u6b3e\u3002\n\n\u70b9\u51fb\u4e0b\u4e00\u6b65\uff0c\u9009\u62e9\u94f6\u884c\uff0c\u5b8c\u6210\u4ed8\u6b3e\u3002</h2>\n<form method=\"post\" action=\"/InCashier.do?action=quickLogin\" id=\"fastpayDirectForm\">\n<input type=\"hidden\" name=\"_token\" value=\"".toCharArray();
    _jsp_string1 = "/css/shouyintai.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n</head>\n\r\n\r\n\r\n\r\n\r\n".toCharArray();
    _jsp_string4 = "\n    <span class=\"syt_hs\">\u8be6\u60c5<A onclick=check1(t1,mt1) href=\"javascript:\"><IMG src=\"images/Arrow_07.gif\" name=\"mt1\" border=0 id=mt1></A>\n    </span></td>\n    <td width=\"42%\">".toCharArray();
    _jsp_string19 = "  -->\n</div>\n</body>\n<script language=\"javascript\">\nfunction clearJS(obj)\n{\nif(obj.value == \"\u672c\u6b21\u4ed8\u6b3e\u51ed\u8bc1\u5c06\u53d1\u9001\u5230\u8be5\u90ae\u7bb1\u6216\u624b\u673a\u4e2d\")\n{\nobj.value = \"\";\nobj.style.color = \"#000000\";\n}\n}\n</script>\n</html>\n".toCharArray();
    _jsp_string16 = "\"/>\n<ul style=\"margin-top:10px; height:80px\">\n\n<li><strong style=\"text-align:right;\">\u90ae\u7bb1\u6216\u624b\u673a\u53f7:</strong></li>\n\n<li style=\"width:230px;\"><input type=\"text\" name=\"buyerUserEmail\" style=\"width:230px;\" class=\"sty_input\" value=\"\u672c\u6b21\u4ed8\u6b3e\u51ed\u8bc1\u5c06\u53d1\u9001\u5230\u8be5\u90ae\u7bb1\u6216\u624b\u673a\u4e2d\" onclick=\"clearJS(this)\" /></li>\n\n<li class=\"sty_xlwz\" style=\"width:290px; \">\u8bf7\u6b63\u786e\u586b\u5199\uff0c\u4ee5\u4fbf\u63a5\u6536\u4ed8\u6b3e\u51ed\u8bc1\u3002</li>\n\n</ul>\n\n<div class=\"anniu\">\n<label for=\"\" class=\"left\"><font color=red>&nbsp;".toCharArray();
    _jsp_string6 = " \u5143</td>\n  </tr>\n</table>\n</h2>\n<h4 id=t1 style=\"display:none\">\n\n<p style=\"padding:10px;\">\u4ea4\u6613\u53f7\uff1a".toCharArray();
    _jsp_string3 = "\n<SCRIPT language=JavaScript type=text/javascript>\n  function check1(obj,menu) {\n    if (obj.style.display=='none')\n\n  {obj.style.display='block';menu.src=\"images/Arrow_08.gif\";}\n\n  else\n\n{obj.style.display='none';menu.src=\"images/Arrow_07.gif\";}\n}\n\nfunction check(obj) {if (obj.style.display=='none') {obj.style.display='block'}else{obj.style.display='none'}}</SCRIPT>\n\n<body>\n<div class=\"main\">\n\r\n<div class=\"top\">\r\n        	<div class=\"logo\"><img src=\"images/ht_logo.jpg\" width=\"284\" height=\"91\" /></div>\r\n            <div class=\"top_rightfont\">\u60a8\u597d\uff1a\u6b22\u8fce\u4f7f\u7528\u6613\u751f\u652f\u4ed8\u6536\u94f6\u53f0\uff01  \u652f\u4ed8\u9047\u5230\u7684\u95ee\u9898\uff1f</div>\r\n</div>\n<div class=\"syt_content\">\n<div class=\"tubxx\">\u60a8\u6b63\u5728\u4f7f\u7528\u5373\u65f6\u5230\u8d26\u4ea4\u6613</div>\n<div class=\"tu_jingdu\"><img src=\"images/olind_1.gif\" width=\"948\" height=\"29\" /></div>\n<div class=\"syt_content\">\n\n<h1>\n<span class=\"left\" style=\"margin-left:20px;\">\u5b9a\u5355\u540d\u79f0</span>\n<span class=\"left\" style=\"margin-left:300px;\">\u6536\u6b3e\u65b9</span>\n<span class=\"right\" style=\"margin-right:100px;\">\u8ba2\u5355\u91d1\u989d</span>\n</h1>\n<h2>\n<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\n  <tr>\n    <td width=\"42%\"><span class=\"left\" style=\"margin-left:40px;\">".toCharArray();
    _jsp_string5 = "</td>\n    <td width=\"16%\">".toCharArray();
    _jsp_string7 = "   \u5546\u54c1\u540d\u79f0(\u6570\u91cf)\uff1a".toCharArray();
    _jsp_string18 = "\r\n<!-- ".toCharArray();
    _jsp_string13 = "\"/>\n<input type=\"hidden\" name=\"_persistence\" value=\"".toCharArray();
    _jsp_string10 = " <br />\n\n\u4ea4\u6613\u91d1\u989d\uff1a".toCharArray();
    _jsp_string2 = "\r\n".toCharArray();
    _jsp_string14 = "\"/>\n<li><strong style=\"text-align:right;\">\u6613\u751f\u652f\u4ed8\u8d26\u6237\u540d:</strong></li>\n\n<li style=\"width:190px;\"><input name=\"buyerUserName\" class=\"sty_input\" type=\"text\" /></li>\n\n<li><a href=\"#\">\u5fd8\u8bb0\u8d26\u6237\u540d\uff1f</a></li>\n\n<li><strong style=\"text-align:right;\">\u652f\u4ed8\u5bc6\u7801:</strong></li>\n\n<li style=\"width:190px;\"><input name=\"password\" class=\"sty_input\" type=\"password\" /></li>\n\n<li><a href=\"#\">\u627e\u56de\u652f\u4ed8\u5bc6\u7801</a></li>\n\n<li class=\"sty_xlwz\" style=\"width:330px; \">\u8bf7\u8f93\u5165\u8d26\u6237\u7684\u652f\u4ed8\u5bc6\u7801\uff0c<span class=\"syt_hs\">\u4e0d\u662f\u767b\u5f55\u5bc6\u7801</span>\u3002</li>\n\n</ul>\n\n<div class=\"anniu\"> <label for=\"\" class=\"left\"><font color=red>&nbsp;".toCharArray();
    _jsp_string11 = "\u5143  \u8d2d\u4e70\u65f6\u95f4\uff1a".toCharArray();
    _jsp_string8 = ") \u8ba2\u5355\u53f7\uff1a".toCharArray();
    _jsp_string12 = " </p>\n\n</h4>\n\n</div>\n\n<div class=\"syt_zck\">\n\n<div class=\"sty_lbt\">\n\n<h1>\u6211\u6709\u6613\u751f\u652f\u4ed8\u8d26\u6237,\u8f7b\u677e\u4ed8\u6b3e:</h1>\n\n<ul>\n<form id=\"fastpayLoginForm\" method=\"post\" action=\"/InCashier.do?action=login\">\n<input type=\"hidden\" name=\"_token\" value=\"".toCharArray();
    _jsp_string0 = "\n\r\n<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n<html>\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n<title>\u6613\u751f\u652f\u4ed8\u6536\u94f6\u53f0</title>\r\n<link href=\"".toCharArray();
    _jsp_string17 = "</font></label>\n<span class=\"next_anniu\" style=\"margin-left:200px\"><a href=\"javascript:document.forms[1].submit();\">\u4e0b\u4e00\u6b65</a></span>\n\n</div>\n\n</div></form>\n\n</div>\n\r\n\r\n<div class=\"foot\">\u5173\u4e8e\u6613\u751f\u652f\u4ed8 | \u7ecf\u9500\u5546\u4f53\u7cfb | \u4f53\u9a8c\u8ba1\u5212 | \u5b98\u65b9\u535a\u5ba2 | \u8bda\u5f81\u82f1\u624d | \u8054\u7cfb\u6211\u4eec | International Business | About EasyPay<br />\r\n          <br />\r\n        \u6613\u751f\u652f\u4ed8\u7248\u6743\u6240\u6709 ICP\u8bc1\uff1a\u6d25ICP\u590711001957\u53f7</div>\r\n </div>\r\n".toCharArray();
    _jsp_string9 = " \u5546\u54c1\u63cf\u8ff0\uff1a".toCharArray();
  }
}
