/*
 * JSP generated by Resin-4.0.42 (built Tue, 20 Jan 2015 08:45:25 PST)
 */

package _jsp._web_22dinf._common;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;

public class _error__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  private boolean _caucho_isNotModified;
  private com.caucho.jsp.PageManager _jsp_pageManager;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    com.caucho.jsp.PageContextImpl pageContext = _jsp_pageManager.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);

    TagState _jsp_state = new TagState();

    try {
      _jspService(request, response, pageContext, _jsp_application, session, _jsp_state);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_state.release();
      _jsp_pageManager.freePageContext(pageContext);
    }
  }
  
  private void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response,
              com.caucho.jsp.PageContextImpl pageContext,
              javax.servlet.ServletContext application,
              javax.servlet.http.HttpSession session,
              TagState _jsp_state)
    throws Throwable
  {
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.jsp.tagext.JspTag _jsp_parent_tag = null;
    com.caucho.jsp.PageContextImpl _jsp_parentContext = pageContext;
    response.setContentType("text/html; charset=utf-8");
    com.caucho.jstl.rt.CoreImportTag _jsp_CoreImportTag_0 = null;
    com.caucho.jstl.el.SetLocaleTag _jsp_SetLocaleTag_1 = null;
    com.caucho.jstl.el.FormatDateTag _jsp_FormatDateTag_2 = null;

    out.write(_jsp_string0, 0, _jsp_string0.length);
    pageContext.requestSetOrRemove("base", "");
    out.write(_jsp_string1, 0, _jsp_string1.length);
    pageContext.sessionSetOrRemove("lang", "i18n/Page");
    out.write(_jsp_string1, 0, _jsp_string1.length);
    pageContext.sessionSetOrRemove("bundle", "i18n/Credit_card");
    out.write(_jsp_string1, 0, _jsp_string1.length);
    pageContext.applicationSetOrRemove("event", "conf/event");
    out.write(_jsp_string1, 0, _jsp_string1.length);
    _jsp_CoreImportTag_0 = _jsp_state.get_jsp_CoreImportTag_0(pageContext, _jsp_parent_tag);
    int _jspEval5 = _jsp_CoreImportTag_0.doStartTag();
    _jsp_CoreImportTag_0.doEndTag();
    out.write(_jsp_string1, 0, _jsp_string1.length);
    if (_caucho_expr_0.evalBoolean(_jsp_env)) {
      out.write(_jsp_string2, 0, _jsp_string2.length);
      _jsp_SetLocaleTag_1 = _jsp_state.get_jsp_SetLocaleTag_1(pageContext, _jsp_parent_tag);
      _jsp_SetLocaleTag_1.doStartTag();
      out.write(_jsp_string2, 0, _jsp_string2.length);
      pageContext.sessionSetOrRemove("locals", "en");
      out.write(_jsp_string1, 0, _jsp_string1.length);
    }
    out.write(_jsp_string3, 0, _jsp_string3.length);
    Object _caucho_loc_object_11;
    _caucho_loc_object_11 = _caucho_expr_1.evalObject(_jsp_env);
    javax.servlet.jsp.jstl.fmt.LocalizationContext _caucho_loc_ctx_12;
    if (_caucho_loc_object_11 instanceof javax.servlet.jsp.jstl.fmt.LocalizationContext)
      _caucho_loc_ctx_12 = (javax.servlet.jsp.jstl.fmt.LocalizationContext)_caucho_loc_object_11;
     else if (_caucho_loc_object_11 instanceof String)
      _caucho_loc_ctx_12 = pageContext.getBundle((String)_caucho_loc_object_11);
    else
      _caucho_loc_ctx_12 = null;

    String _caucho_message_13;
    if (_caucho_loc_ctx_12 != null) {
      java.util.Locale _caucho_locale_14= _caucho_loc_ctx_12.getLocale();
      if (_caucho_locale_14 != null)
        com.caucho.jstl.rt.I18NSupport.setResponseLocale(pageContext, _caucho_locale_14);
      _caucho_message_13 = pageContext.getLocalizedMessage(_caucho_loc_ctx_12, "error_msg", null, null);
    }
    else {
      _caucho_message_13 = pageContext.getLocalizedMessage(null, "error_msg", null, null);
    }

    out.print(_caucho_message_13);
    out.write(_jsp_string4, 0, _jsp_string4.length);
    if (_caucho_expr_2.evalBoolean(_jsp_env)) {
      out.write(_jsp_string5, 0, _jsp_string5.length);
      _caucho_expr_3.print(out, _jsp_env, false);
      out.write(_jsp_string6, 0, _jsp_string6.length);
    }
    else {
      out.write(_jsp_string7, 0, _jsp_string7.length);
      _caucho_expr_4.print(out, _jsp_env, false);
      out.write(_jsp_string6, 0, _jsp_string6.length);
    }
    out.write(_jsp_string8, 0, _jsp_string8.length);
    Object _caucho_loc_object_15;
    _caucho_loc_object_15 = _caucho_expr_1.evalObject(_jsp_env);
    javax.servlet.jsp.jstl.fmt.LocalizationContext _caucho_loc_ctx_16;
    if (_caucho_loc_object_15 instanceof javax.servlet.jsp.jstl.fmt.LocalizationContext)
      _caucho_loc_ctx_16 = (javax.servlet.jsp.jstl.fmt.LocalizationContext)_caucho_loc_object_15;
     else if (_caucho_loc_object_15 instanceof String)
      _caucho_loc_ctx_16 = pageContext.getBundle((String)_caucho_loc_object_15);
    else
      _caucho_loc_ctx_16 = null;

    String _caucho_message_17;
    if (_caucho_loc_ctx_16 != null) {
      java.util.Locale _caucho_locale_18= _caucho_loc_ctx_16.getLocale();
      if (_caucho_locale_18 != null)
        com.caucho.jstl.rt.I18NSupport.setResponseLocale(pageContext, _caucho_locale_18);
      _caucho_message_17 = pageContext.getLocalizedMessage(_caucho_loc_ctx_16, "error_id", null, null);
    }
    else {
      _caucho_message_17 = pageContext.getLocalizedMessage(null, "error_id", null, null);
    }

    out.print(_caucho_message_17);
    out.write(_jsp_string9, 0, _jsp_string9.length);
    if (_caucho_expr_5.evalBoolean(_jsp_env)) {
      _caucho_expr_4.print(out, _jsp_env, false);
      out.write(_jsp_string6, 0, _jsp_string6.length);
    }
    else {
      out.write(_jsp_string10, 0, _jsp_string10.length);
    }
    out.write(_jsp_string11, 0, _jsp_string11.length);
    if (_caucho_expr_6.evalBoolean(_jsp_env)) {
      out.write(_jsp_string12, 0, _jsp_string12.length);
    }
    out.write(_jsp_string13, 0, _jsp_string13.length);
    if (_caucho_expr_7.evalBoolean(_jsp_env)) {
      out.write(_jsp_string14, 0, _jsp_string14.length);
    }
    out.write(_jsp_string15, 0, _jsp_string15.length);
    java.util.Date now;
    now = (java.util.Date) pageContext.getAttribute("now");
    if (now == null) {
      now = new java.util.Date();
      pageContext.setAttribute("now", now);
    }
    out.write(_jsp_string16, 0, _jsp_string16.length);
    _jsp_FormatDateTag_2 = _jsp_state.get_jsp_FormatDateTag_2(pageContext, _jsp_parent_tag);
    _jsp_FormatDateTag_2.setValue(_caucho_expr_8);
    _jsp_FormatDateTag_2.doEndTag();
    out.write(_jsp_string17, 0, _jsp_string17.length);
  }

  private com.caucho.make.DependencyContainer _caucho_depends
    = new com.caucho.make.DependencyContainer();

  public java.util.ArrayList<com.caucho.vfs.Dependency> _caucho_getDependList()
  {
    return _caucho_depends.getDependencies();
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    _caucho_depends.add(depend);
  }

  protected void _caucho_setNeverModified(boolean isNotModified)
  {
    _caucho_isNotModified = true;
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;

    if (_caucho_isNotModified)
      return false;

    if (com.caucho.server.util.CauchoSystem.getVersionId() != 7031370602740370491L)
      return true;

    return _caucho_depends.isModified();
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
    TagState tagState;
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("WEB-INF/common/error.jsp"), -8423380287821441182L, false);
    _caucho_depends.add(depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("common/tags.jsp"), -3608291857756734149L, false);
    _caucho_depends.add(depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("common/head.jsp"), 2788524230956787085L, false);
    _caucho_depends.add(depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("common/tail.jsp"), 5980026621458825039L, false);
    _caucho_depends.add(depend);
    depend = new com.caucho.vfs.Depend(mergePath.lookup("jar:file:/c:/dtools/resin-4.0.42/resin-4.0.42/lib/resin.jar!/com/caucho/jstl/core-el.tld"), 7138117085633323267L, false);
    _caucho_depends.add(depend);
    _caucho_depends.add(new com.caucho.make.ClassDependency("com.caucho.jstl.rt.CoreImportTag", 2662537511146645850L));
    depend = new com.caucho.vfs.Depend(mergePath.lookup("jar:file:/c:/dtools/resin-4.0.42/resin-4.0.42/lib/resin.jar!/com/caucho/jstl/fmt-el.tld"), -449626256852172091L, false);
    _caucho_depends.add(depend);
    _caucho_depends.add(new com.caucho.make.ClassDependency("com.caucho.jstl.el.SetLocaleTag", 7903057615573185913L));
    _caucho_depends.add(new com.caucho.make.ClassDependency("com.caucho.jstl.el.FormatDateTag", 5899277161707882428L));
  }

  static {
    try {
    } catch (Exception e) {
      e.printStackTrace();
      throw new RuntimeException(e);
    }
  }

  final static class TagState {
    private com.caucho.jstl.rt.CoreImportTag _jsp_CoreImportTag_0;

    final com.caucho.jstl.rt.CoreImportTag get_jsp_CoreImportTag_0(PageContext pageContext, javax.servlet.jsp.tagext.JspTag _jsp_parent_tag) throws Throwable
    {
      if (_jsp_CoreImportTag_0 == null) {
        _jsp_CoreImportTag_0 = new com.caucho.jstl.rt.CoreImportTag();
        _jsp_CoreImportTag_0.setPageContext(pageContext);
        if (_jsp_parent_tag instanceof javax.servlet.jsp.tagext.Tag)
          _jsp_CoreImportTag_0.setParent((javax.servlet.jsp.tagext.Tag) _jsp_parent_tag);
        else if (_jsp_parent_tag instanceof javax.servlet.jsp.tagext.SimpleTag)
          _jsp_CoreImportTag_0.setParent(new javax.servlet.jsp.tagext.TagAdapter((javax.servlet.jsp.tagext.SimpleTag) _jsp_parent_tag));
        else
          _jsp_CoreImportTag_0.setParent((javax.servlet.jsp.tagext.Tag) null);
        _jsp_CoreImportTag_0.setURL("/common/style.jsp");
        _jsp_CoreImportTag_0.setScope("application");
      }

      return _jsp_CoreImportTag_0;
    }
    private com.caucho.jstl.el.SetLocaleTag _jsp_SetLocaleTag_1;

    final com.caucho.jstl.el.SetLocaleTag get_jsp_SetLocaleTag_1(PageContext pageContext, javax.servlet.jsp.tagext.JspTag _jsp_parent_tag) throws Throwable
    {
      if (_jsp_SetLocaleTag_1 == null) {
        _jsp_SetLocaleTag_1 = new com.caucho.jstl.el.SetLocaleTag();
        _jsp_SetLocaleTag_1.setPageContext(pageContext);
        if (_jsp_parent_tag instanceof javax.servlet.jsp.tagext.Tag)
          _jsp_SetLocaleTag_1.setParent((javax.servlet.jsp.tagext.Tag) _jsp_parent_tag);
        else if (_jsp_parent_tag instanceof javax.servlet.jsp.tagext.SimpleTag)
          _jsp_SetLocaleTag_1.setParent(new javax.servlet.jsp.tagext.TagAdapter((javax.servlet.jsp.tagext.SimpleTag) _jsp_parent_tag));
        else
          _jsp_SetLocaleTag_1.setParent((javax.servlet.jsp.tagext.Tag) null);
        _jsp_SetLocaleTag_1.setValue(_caucho_expr_9);
      }

      return _jsp_SetLocaleTag_1;
    }
    private com.caucho.jstl.el.FormatDateTag _jsp_FormatDateTag_2;

    final com.caucho.jstl.el.FormatDateTag get_jsp_FormatDateTag_2(PageContext pageContext, javax.servlet.jsp.tagext.JspTag _jsp_parent_tag) throws Throwable
    {
      if (_jsp_FormatDateTag_2 == null) {
        _jsp_FormatDateTag_2 = new com.caucho.jstl.el.FormatDateTag();
        _jsp_FormatDateTag_2.setPageContext(pageContext);
        if (_jsp_parent_tag instanceof javax.servlet.jsp.tagext.Tag)
          _jsp_FormatDateTag_2.setParent((javax.servlet.jsp.tagext.Tag) _jsp_parent_tag);
        else if (_jsp_parent_tag instanceof javax.servlet.jsp.tagext.SimpleTag)
          _jsp_FormatDateTag_2.setParent(new javax.servlet.jsp.tagext.TagAdapter((javax.servlet.jsp.tagext.SimpleTag) _jsp_parent_tag));
        else
          _jsp_FormatDateTag_2.setParent((javax.servlet.jsp.tagext.Tag) null);
        _jsp_FormatDateTag_2.setType(_caucho_expr_10);
      }

      return _jsp_FormatDateTag_2;
    }

    void release()
    {
      if (_jsp_CoreImportTag_0 != null) {
        _jsp_CoreImportTag_0.release();
        _jsp_CoreImportTag_0 = null;
      }
      if (_jsp_SetLocaleTag_1 != null) {
        _jsp_SetLocaleTag_1.release();
        _jsp_SetLocaleTag_1 = null;
      }
      if (_jsp_FormatDateTag_2 != null) {
        _jsp_FormatDateTag_2.release();
        _jsp_FormatDateTag_2 = null;
      }
    }
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void caucho_init(ServletConfig config)
  {
    try {
      com.caucho.server.webapp.WebApp webApp
        = (com.caucho.server.webapp.WebApp) config.getServletContext();
      init(config);
      if (com.caucho.jsp.JspManager.getCheckInterval() >= 0)
        _caucho_depends.setCheckInterval(com.caucho.jsp.JspManager.getCheckInterval());
      _jsp_pageManager = webApp.getJspApplicationContext().getPageManager();
      com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
      manager.addTaglibFunctions(_jsp_functionMap, "spring", "http://www.springframework.org/tags");
      manager.addTaglibFunctions(_jsp_functionMap, "c", "http://java.sun.com/jstl/core");
      manager.addTaglibFunctions(_jsp_functionMap, "fmt", "http://java.sun.com/jstl/fmt");
      manager.addTaglibFunctions(_jsp_functionMap, "fn", "http://java.sun.com/jsp/jstl/functions");
      com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.InitPageContextImpl(webApp, this);
      _caucho_expr_0 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${sessionScope.e_lang!='CN'&&sessionScope.e_lang!=null}");
      _caucho_expr_1 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${lang}");
      _caucho_expr_2 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${we.eventid-1>0}");
      _caucho_expr_3 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${we.eventmsg}");
      _caucho_expr_4 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${we.eventid}");
      _caucho_expr_5 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${we.eventid-1>\r\n			                0}");
      _caucho_expr_6 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${fn:substring(we.eventid,0,1)==3}");
      _caucho_expr_7 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${fn:substring(we.eventid,0,1)!=3}");
      _caucho_expr_8 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${now}");
      _caucho_expr_9 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "zh_US");
      _caucho_expr_10 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "both");
    } catch (Exception e) {
      throw com.caucho.config.ConfigException.create(e);
    }
  }
  private static com.caucho.el.Expr _caucho_expr_0;
  private static com.caucho.el.Expr _caucho_expr_1;
  private static com.caucho.el.Expr _caucho_expr_2;
  private static com.caucho.el.Expr _caucho_expr_3;
  private static com.caucho.el.Expr _caucho_expr_4;
  private static com.caucho.el.Expr _caucho_expr_5;
  private static com.caucho.el.Expr _caucho_expr_6;
  private static com.caucho.el.Expr _caucho_expr_7;
  private static com.caucho.el.Expr _caucho_expr_8;
  private static com.caucho.el.Expr _caucho_expr_9;
  private static com.caucho.el.Expr _caucho_expr_10;

  private final static char []_jsp_string4;
  private final static char []_jsp_string8;
  private final static char []_jsp_string11;
  private final static char []_jsp_string9;
  private final static char []_jsp_string7;
  private final static char []_jsp_string14;
  private final static char []_jsp_string13;
  private final static char []_jsp_string2;
  private final static char []_jsp_string5;
  private final static char []_jsp_string12;
  private final static char []_jsp_string10;
  private final static char []_jsp_string3;
  private final static char []_jsp_string0;
  private final static char []_jsp_string16;
  private final static char []_jsp_string6;
  private final static char []_jsp_string15;
  private final static char []_jsp_string1;
  private final static char []_jsp_string17;
  static {
    _jsp_string4 = ":\r\n      					<span>".toCharArray();
    _jsp_string8 = "   \r\n			            ".toCharArray();
    _jsp_string11 = "       \r\n               		 </span>\r\n                		 ".toCharArray();
    _jsp_string9 = "!\r\n			            ".toCharArray();
    _jsp_string7 = "\r\n			                ".toCharArray();
    _jsp_string14 = "\r\n				        	<p class=\"pdleft8 blue\" style=\"cursor:pointer\"><a onclick=\"javascript:window.close()\">\u70b9\u51fb\u6b64\u5904\u5173\u95ed</a></p>\r\n				        ".toCharArray();
    _jsp_string13 = "\r\n				        ".toCharArray();
    _jsp_string2 = "\r\n  ".toCharArray();
    _jsp_string5 = "\r\n			               ".toCharArray();
    _jsp_string12 = "\r\n				        	<p class=\"pdleft8 blue\" style=\"cursor:pointer\"><a onclick=\"javascript:history.back()\">\u70b9\u51fb\u6b64\u5904\u8fd4\u56de</a></p>\r\n				        ".toCharArray();
    _jsp_string10 = "\r\n			                800000\r\n			              ".toCharArray();
    _jsp_string3 = "\r\n\r\n<body>\r\n\r\n\r\n<div class=\"PAY_InHeader\">\r\n    <div class=\"topBarArea\">\r\n        <div class=\"topBar\"><a target=\"_blank\" href=\"http://www.gigold.com\">\u5409\u9ad8\u9996\u9875</a></div>\r\n    </div>\r\n    <div class=\"contentArea\">\r\n        <div class=\"logo\"></div>\r\n    </div>\r\n</div>\r\n\r\n\r\n<div class=\"InContent\">\r\n	<div class=\"boxContent\">\r\n\r\n        <div class=\"errorContent\">\r\n            <div class=\"dialogTipsArea\">\r\n                <span class=\"TipIco_error\"></span>\r\n                <span class=\"TipText\">\r\n                	   	".toCharArray();
    _jsp_string0 = "\r\n\r\n\r\n\r\n\r\n\r\n".toCharArray();
    _jsp_string16 = "-->\r\n<!-- ".toCharArray();
    _jsp_string6 = "\r\n			              ".toCharArray();
    _jsp_string15 = "	\r\n				     </span>   \r\n                <div style=\"clear:both\"></div>\r\n            </div>\r\n\r\n\r\n            <div class=\"helpQA\">\r\n                <div class=\"help_question\">\u4ed8\u6b3e\u6ca1\u6709\u6210\u529f\uff1f</div>\r\n                <div class=\"help_answer\">\u8bf7\u5230\u7f51\u4e0a\u94f6\u884c\u67e5\u770b\u60a8\u7684\u94f6\u884c\u5361\u6709\u6ca1\u6709\u6263\u6b3e\u3002\u53bb\u00bb \u94f6\u884c\u54a8\u8be2\u7535\u8bdd\uff1a</div>\r\n\r\n                <div class=\"help_question\">\u94f6\u884c\u5df2\u6263\u6b3e\uff0c\u4f46\u6ca1\u6709\u63d0\u793a\u6210\u529f\uff1f</div>\r\n                <div class=\"help_answer\">\u7531\u4e8e\u7f51\u7edc\u4f20\u8f93\u95ee\u9898\u9020\u6210\uff0c\u8bf7\u70b9\u51fb\u4ea4\u6613\u7ed3\u679c\u67e5\u8be2\uff0c\u6211\u4eec\u4e3a\u60a8\u6062\u590d\u6b64\u4ea4\u6613\u3002</div>\r\n\r\n                <div class=\"help_question\">\u94f6\u884c\u6ca1\u6709\u6263\u6b3e\uff1f</div>\r\n                <div class=\"help_answer\">\u5efa\u8bae\u60a8\u91cd\u65b0\u652f\u4ed8\u4e00\u6b21\u8bd5\u8bd5\u770b\uff0c\u5982\u679c\u4ecd\u65e0\u6cd5\u6210\u529f,<br>\r\n            \u8bf7\u54a8\u8be2\u670d\u52a1:400-022-6816</div>\r\n            </div>\r\n        </div>\r\n\r\n     \r\n    </div>\r\n\r\n\r\n\r\n\r\n</div>\r\n\r\n\r\n\r\n<!--<div class=\"foot\">\u5173\u4e8e\u5409\u5361   | \u7ecf\u9500\u5546\u4f53\u7cfb | \u4f53\u9a8c\u8ba1\u5212 | \u5b98\u65b9\u535a\u5ba2 | \u8bda\u5f81\u82f1\u624d | \u8054\u7cfb\u6211\u4eec | International Business | About\u5409\u5361<br />-->\r\n<!--          <br />-->\r\n<!--        \u5409\u5361\u7248\u6743\u6240\u6709 ICP\u8bc1\uff1a\u4eacICP\u590713002947\u53f7</div>-->\r\n<!-- </div>-->\r\n<!--".toCharArray();
    _jsp_string1 = "\r\n".toCharArray();
    _jsp_string17 = "  -->\r\n    <div class=\"copyright\">\r\n    	<div class=\"adress\">Copyright @ since 2014 All Rights Reserved \u7248\u6743\u6240\u6709 \u4fb5\u6743\u5fc5\u7a76 \u5929\u6d25\u5409\u9ad8\u5728\u7ebf\u652f\u4ed8\u6280\u672f\u6709\u9650\u516c\u53f8<br /> \r\n\u6d25ICP\u590713003754\u53f7-1</div>\r\n        <div class=\"bottomMenu\"><a href=\"#\">\u5173\u4e8e\u6211\u4eec</a> | <a href=\"#\">\u5546\u52a1\u5408\u4f5c</a> | <a href=\"#\">\u8054\u7cfb\u6211\u4eec</a> | <a href=\"#\">\u5b89\u5168\u8054\u76df</a></div>\r\n    </div>\r\n    <div class=\"clearFloat\"></div>\r\n\r\n</body>\r\n\r\n</html>\r\n".toCharArray();
  }
}
