/*
 * JSP generated by Resin-4.0.42 (built Tue, 20 Jan 2015 08:45:25 PST)
 */

package _jsp._web_22dinf._common;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;

public class _forbank__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  private boolean _caucho_isNotModified;
  private com.caucho.jsp.PageManager _jsp_pageManager;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    com.caucho.jsp.PageContextImpl pageContext = _jsp_pageManager.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);

    TagState _jsp_state = new TagState();

    try {
      _jspService(request, response, pageContext, _jsp_application, session, _jsp_state);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_state.release();
      _jsp_pageManager.freePageContext(pageContext);
    }
  }
  
  private void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response,
              com.caucho.jsp.PageContextImpl pageContext,
              javax.servlet.ServletContext application,
              javax.servlet.http.HttpSession session,
              TagState _jsp_state)
    throws Throwable
  {
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.jsp.tagext.JspTag _jsp_parent_tag = null;
    com.caucho.jsp.PageContextImpl _jsp_parentContext = pageContext;
    response.setContentType("text/html; charset=utf-8");
    com.caucho.jstl.el.SetLocaleTag _jsp_SetLocaleTag_0 = null;

    out.write(_jsp_string0, 0, _jsp_string0.length);
    pageContext.requestSetOrRemove("base", "");
    out.write(_jsp_string1, 0, _jsp_string1.length);
    pageContext.sessionSetOrRemove("lang", "i18n/Page");
    out.write(_jsp_string1, 0, _jsp_string1.length);
    pageContext.sessionSetOrRemove("bundle", "i18n/Credit_card");
    out.write(_jsp_string2, 0, _jsp_string2.length);
    _caucho_expr_0.print(out, _jsp_env, false);
    out.write(_jsp_string3, 0, _jsp_string3.length);
    _caucho_expr_0.print(out, _jsp_env, false);
    out.write(_jsp_string4, 0, _jsp_string4.length);
    _caucho_expr_0.print(out, _jsp_env, false);
    out.write(_jsp_string5, 0, _jsp_string5.length);
    _caucho_expr_0.print(out, _jsp_env, false);
    out.write(_jsp_string6, 0, _jsp_string6.length);
    _jsp_SetLocaleTag_0 = _jsp_state.get_jsp_SetLocaleTag_0(pageContext, _jsp_parent_tag);
    _jsp_SetLocaleTag_0.setValue(_caucho_expr_1);
    _jsp_SetLocaleTag_0.doStartTag();
    out.write(_jsp_string7, 0, _jsp_string7.length);
    Object _caucho_loc_object_5;
    _caucho_loc_object_5 = _caucho_expr_2.evalObject(_jsp_env);
    javax.servlet.jsp.jstl.fmt.LocalizationContext _caucho_loc_ctx_6;
    if (_caucho_loc_object_5 instanceof javax.servlet.jsp.jstl.fmt.LocalizationContext)
      _caucho_loc_ctx_6 = (javax.servlet.jsp.jstl.fmt.LocalizationContext)_caucho_loc_object_5;
     else if (_caucho_loc_object_5 instanceof String)
      _caucho_loc_ctx_6 = pageContext.getBundle((String)_caucho_loc_object_5);
    else
      _caucho_loc_ctx_6 = null;

    String _caucho_message_7;
    if (_caucho_loc_ctx_6 != null) {
      java.util.Locale _caucho_locale_8= _caucho_loc_ctx_6.getLocale();
      if (_caucho_locale_8 != null)
        com.caucho.jstl.rt.I18NSupport.setResponseLocale(pageContext, _caucho_locale_8);
      _caucho_message_7 = pageContext.getLocalizedMessage(_caucho_loc_ctx_6, "communication_bank", null, null);
    }
    else {
      _caucho_message_7 = pageContext.getLocalizedMessage(null, "communication_bank", null, null);
    }

    out.print(_caucho_message_7);
    out.write(_jsp_string8, 0, _jsp_string8.length);
    _caucho_expr_3.print(out, _jsp_env, false);
    out.write(_jsp_string9, 0, _jsp_string9.length);
    _caucho_expr_4.print(out, _jsp_env, false);
    out.write(_jsp_string10, 0, _jsp_string10.length);
  }

  private com.caucho.make.DependencyContainer _caucho_depends
    = new com.caucho.make.DependencyContainer();

  public java.util.ArrayList<com.caucho.vfs.Dependency> _caucho_getDependList()
  {
    return _caucho_depends.getDependencies();
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    _caucho_depends.add(depend);
  }

  protected void _caucho_setNeverModified(boolean isNotModified)
  {
    _caucho_isNotModified = true;
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;

    if (_caucho_isNotModified)
      return false;

    if (com.caucho.server.util.CauchoSystem.getVersionId() != 7031370602740370491L)
      return true;

    return _caucho_depends.isModified();
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
    TagState tagState;
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("WEB-INF/common/forbank.jsp"), -7971272322873066373L, false);
    _caucho_depends.add(depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("common/tags.jsp"), -3608291857756734149L, false);
    _caucho_depends.add(depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("common/style.jsp"), -8516269833883808472L, false);
    _caucho_depends.add(depend);
    depend = new com.caucho.vfs.Depend(mergePath.lookup("jar:file:/e:/Program%20Files/resin-4.0.42/resin-4.0.42/lib/resin.jar!/com/caucho/jstl/fmt-el.tld"), -449626256852172091L, false);
    _caucho_depends.add(depend);
    _caucho_depends.add(new com.caucho.make.ClassDependency("com.caucho.jstl.el.SetLocaleTag", 7903057615573185913L));
  }

  static {
    try {
    } catch (Exception e) {
      e.printStackTrace();
      throw new RuntimeException(e);
    }
  }

  final static class TagState {
    private com.caucho.jstl.el.SetLocaleTag _jsp_SetLocaleTag_0;

    final com.caucho.jstl.el.SetLocaleTag get_jsp_SetLocaleTag_0(PageContext pageContext, javax.servlet.jsp.tagext.JspTag _jsp_parent_tag) throws Throwable
    {
      if (_jsp_SetLocaleTag_0 == null) {
        _jsp_SetLocaleTag_0 = new com.caucho.jstl.el.SetLocaleTag();
        _jsp_SetLocaleTag_0.setPageContext(pageContext);
        if (_jsp_parent_tag instanceof javax.servlet.jsp.tagext.Tag)
          _jsp_SetLocaleTag_0.setParent((javax.servlet.jsp.tagext.Tag) _jsp_parent_tag);
        else if (_jsp_parent_tag instanceof javax.servlet.jsp.tagext.SimpleTag)
          _jsp_SetLocaleTag_0.setParent(new javax.servlet.jsp.tagext.TagAdapter((javax.servlet.jsp.tagext.SimpleTag) _jsp_parent_tag));
        else
          _jsp_SetLocaleTag_0.setParent((javax.servlet.jsp.tagext.Tag) null);
      }

      return _jsp_SetLocaleTag_0;
    }

    void release()
    {
      if (_jsp_SetLocaleTag_0 != null) {
        _jsp_SetLocaleTag_0.release();
        _jsp_SetLocaleTag_0 = null;
      }
    }
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void caucho_init(ServletConfig config)
  {
    try {
      com.caucho.server.webapp.WebApp webApp
        = (com.caucho.server.webapp.WebApp) config.getServletContext();
      init(config);
      if (com.caucho.jsp.JspManager.getCheckInterval() >= 0)
        _caucho_depends.setCheckInterval(com.caucho.jsp.JspManager.getCheckInterval());
      _jsp_pageManager = webApp.getJspApplicationContext().getPageManager();
      com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
      manager.addTaglibFunctions(_jsp_functionMap, "spring", "http://www.springframework.org/tags");
      manager.addTaglibFunctions(_jsp_functionMap, "c", "http://java.sun.com/jstl/core");
      manager.addTaglibFunctions(_jsp_functionMap, "fmt", "http://java.sun.com/jstl/fmt");
      manager.addTaglibFunctions(_jsp_functionMap, "fn", "http://java.sun.com/jsp/jstl/functions");
      com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.InitPageContextImpl(webApp, this);
      _caucho_expr_0 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${base}");
      _caucho_expr_1 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "zh_${page.locale}");
      _caucho_expr_2 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${lang}");
      _caucho_expr_3 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${page.form}");
      _caucho_expr_4 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${page.bank}");
    } catch (Exception e) {
      throw com.caucho.config.ConfigException.create(e);
    }
  }
  private static com.caucho.el.Expr _caucho_expr_0;
  private static com.caucho.el.Expr _caucho_expr_1;
  private static com.caucho.el.Expr _caucho_expr_2;
  private static com.caucho.el.Expr _caucho_expr_3;
  private static com.caucho.el.Expr _caucho_expr_4;

  private final static char []_jsp_string7;
  private final static char []_jsp_string10;
  private final static char []_jsp_string8;
  private final static char []_jsp_string3;
  private final static char []_jsp_string0;
  private final static char []_jsp_string5;
  private final static char []_jsp_string9;
  private final static char []_jsp_string4;
  private final static char []_jsp_string1;
  private final static char []_jsp_string6;
  private final static char []_jsp_string2;
  static {
    _jsp_string7 = "\r\n<html>\r\n<head>\r\n<style>\r\nbody{background:#f0f0f0}\r\n</style>\r\n</head>\r\n\r\n<script LANGUAGE=\"JavaScript\">\r\n  window.status=\"".toCharArray();
    _jsp_string10 = "</span></strong>  -->\u94f6\u884c\u9875\u9762\u52a0\u8f7d\u4e2d\uff0c\u8bf7\u7a0d\u5019...</p>\r\n          <p><img src=\"images/img/loading.gif\" width=\"280\" height=\"13\" /></p>\r\n          <p>\u5982\u679c\u7cfb\u7edf\u957f\u65f6\u95f4\u505c\u6b62\u54cd\u5e94<strong><span class=\"red\"><a href=\"javascript:window.close();\">\u5355\u51fb\u6b64\u5904</a></span></strong>\u5173\u95ed\u672c\u7a97\u53e3\u91cd\u65b0\u9009\u62e9\u94f6\u884c\u652f\u4ed8</p>\r\n        </div>\r\n        <div class=\"quern_link2\">\u4e86\u89e3\u66f4\u591a\u5409\u9ad8\u76f8\u5173\u4ea7\u54c1\u8bf7\u767b\u9646\u5409\u9ad8\u5b98\u7f51\uff1awww.gicard.net</div>\r\n</div>\r\n</body>\r\n</html>\r\n".toCharArray();
    _jsp_string8 = "\";\r\n  window.focus();\r\n</script>\r\n\r\n<body>\r\n<div class=\"queren\">\r\n".toCharArray();
    _jsp_string3 = "/css/style.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n<link href=\"".toCharArray();
    _jsp_string0 = "\r\n\r\n\r\n\r\n\r\n\r\n".toCharArray();
    _jsp_string5 = "/css/common.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n<link href=\"".toCharArray();
    _jsp_string9 = "\r\n    	<div class=\"quern_yes\" style=\"margin-top:80px\">\r\n    	  <p><span class=\"qunrenzit red\"><!-- <strong><span class=\"blue\">".toCharArray();
    _jsp_string4 = "/css/cash.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n\r\n<link href=\"".toCharArray();
    _jsp_string1 = "\r\n".toCharArray();
    _jsp_string6 = "/css/payFor.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n\r\n<style type=\"text/css\">\r\n\r\n.table_ui thead th {\r\ncolor: #333;\r\npadding: 8px 10px;\r\nfont-size: 12px;\r\ntext-align: center;\r\nbackground: #f5f5f5;\r\nfont-weight: normal;\r\nborder: 1px solid #DBDBDB;\r\n}\r\n\r\n.table_ui  th {\r\ncolor: #333;\r\npadding: 8px 10px;\r\nfont-size: 12px;\r\ntext-align: center;\r\nbackground: #f5f5f5;\r\nfont-weight: normal;\r\nborder: 1px solid #DBDBDB;\r\n}\r\n\r\n.table_ui {\r\nborder-collapse: collapse;\r\nborder: 1px solid #DBDBDB;\r\nfont-family: Arial, Helvetica, sans-serif;\r\n}\r\n\r\n.table_ui td {\r\ntext-align: center;\r\npadding: 4px 10px;\r\nborder: 1px solid #DBDBDB;\r\nfont-size: 12px;\r\nline-height: 26px;\r\n}\r\n\r\n</style>\r\n\r\n<script language=\"javascript\" src=\"/js/jquery-1.7.js\"></script>\r\n<script language=\"javascript\" src=\"/js/jqstyle.js\"></script>\r\n</head>\r\n\r\n\r\n\r\n".toCharArray();
    _jsp_string2 = "\r\n\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n<meta http-equiv=\"X-UA-Compatible\" content=\"IE=Edge\">\r\n<title></title> \r\n<link href=\"".toCharArray();
  }
}
