/*
 * JSP generated by Resin-3.0.22 (built Mon, 13 Nov 2006 09:32:38 PST)
 */

package _jsp._web_22dinf._common;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;

public class _resultcmbc_0b2b__jsp extends com.caucho.jsp.JavaPage{
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.Application _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = com.caucho.jsp.QJspFactory.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html; charset=utf-8");
    request.setCharacterEncoding("UTF-8");
    com.caucho.jstl.el.SetLocaleTag _jsp_SetLocaleTag_0 = null;
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.requestSetOrRemove("base", "");
      out.write(_jsp_string1, 0, _jsp_string1.length);
      pageContext.sessionSetOrRemove("lang", "i18n/Page");
      out.write(_jsp_string1, 0, _jsp_string1.length);
      pageContext.sessionSetOrRemove("bundle", "i18n/Credit_card");
      out.write(_jsp_string2, 0, _jsp_string2.length);
      _caucho_expr_0.print(out, pageContext, false);
      out.write(_jsp_string3, 0, _jsp_string3.length);
      _caucho_expr_0.print(out, pageContext, false);
      out.write(_jsp_string4, 0, _jsp_string4.length);
      if (_jsp_SetLocaleTag_0 == null) {
        _jsp_SetLocaleTag_0 = new com.caucho.jstl.el.SetLocaleTag();
        _jsp_SetLocaleTag_0.setPageContext(pageContext);
        _jsp_SetLocaleTag_0.setParent((javax.servlet.jsp.tagext.Tag) null);
      }

      _jsp_SetLocaleTag_0.setValue(_caucho_expr_1);
      _jsp_SetLocaleTag_0.doStartTag();
      out.write(_jsp_string5, 0, _jsp_string5.length);
      _caucho_expr_2.print(out, pageContext, false);
      out.write(_jsp_string6, 0, _jsp_string6.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      if (_jsp_SetLocaleTag_0 != null)
        _jsp_SetLocaleTag_0.release();
      com.caucho.jsp.QJspFactory.freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.make.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.util.CauchoSystem.getVersionId() != -3988812337524854005L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.make.Dependency depend;
      depend = (com.caucho.make.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("WEB-INF/common/resultCMBC_B2B.jsp"), 1737382394105338191L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("common/tags.jsp"), -3608291857756734149L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("common/style.jsp"), 6728541205109573701L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    depend = new com.caucho.vfs.Depend(mergePath.lookup("E:/appstools/resin-3.0.22/lib/resin.jar"), 8088847092149864614L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, new com.caucho.make.ClassDependency(com.caucho.jstl.el.SetLocaleTag.class, 4701593291462471091L));
  }
  private final static com.caucho.el.Expr _caucho_expr_0 =
    new com.caucho.el.IdExpr("base");
  private final static com.caucho.el.Expr _caucho_expr_1 =
    new com.caucho.el.InterpolateExpr(new com.caucho.el.StringLiteral("zh_"), new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("page"), new com.caucho.el.StringLiteral("locale")), "page.locale"));
  private final static com.caucho.el.Expr _caucho_expr_2 =
    new com.caucho.el.PathExpr(new com.caucho.el.ArrayExpr(new com.caucho.el.IdExpr("page"), new com.caucho.el.StringLiteral("form")), "page.form");

  private final static char []_jsp_string2;
  private final static char []_jsp_string1;
  private final static char []_jsp_string4;
  private final static char []_jsp_string3;
  private final static char []_jsp_string5;
  private final static char []_jsp_string0;
  private final static char []_jsp_string6;
  static {
    _jsp_string2 = "\r\n\r\n<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n<html>\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n<title>\u878d\u5b9d\u6536\u94f6\u53f0</title>\r\n<link href=\"".toCharArray();
    _jsp_string1 = "\r\n".toCharArray();
    _jsp_string4 = "/css/cash.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n<meta http-equiv=\"X-UA-Compatible\" content=\"IE=EmulateIE7\" />\r\n<script language=\"javascript\" src=\"/js/jquery-1.7.js\"></script>\r\n<script language=\"javascript\" src=\"/js/jqstyle.js\"></script>\r\n</head>\r\n\r\n\r\n\r\n".toCharArray();
    _jsp_string3 = "/css/style.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n<link href=\"".toCharArray();
    _jsp_string5 = "\r\n<style type=\"text/css\">\r\nbody{background:#eeeeee}\r\n</style>\r\n<body>\r\n        <div class=\"queren\">    	\r\n           ".toCharArray();
    _jsp_string0 = "\r\n\r\n\r\n\r\n\r\n\r\n".toCharArray();
    _jsp_string6 = "\r\n         <div class=\"quern_link\">\u4e86\u89e3\u66f4\u591a\u878d\u5b9d\u76f8\u5173\u4ea7\u54c1\u8bf7\u767b\u9646\u878d\u5b9d\u5b98\u7f51\uff1awww.reapal.com</div>\r\n      </div>    \r\n  </body>\r\n\r\n</html>\r\n".toCharArray();
  }
}
