/*
 * JSP generated by Resin-4.0.42 (built Tue, 20 Jan 2015 08:45:25 PST)
 */

package _jsp._web_22dinf._v4;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;

public class _redirect__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  private boolean _caucho_isNotModified;
  private com.caucho.jsp.PageManager _jsp_pageManager;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    com.caucho.jsp.PageContextImpl pageContext = _jsp_pageManager.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);

    TagState _jsp_state = new TagState();

    try {
      _jspService(request, response, pageContext, _jsp_application, session, _jsp_state);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_state.release();
      _jsp_pageManager.freePageContext(pageContext);
    }
  }
  
  private void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response,
              com.caucho.jsp.PageContextImpl pageContext,
              javax.servlet.ServletContext application,
              javax.servlet.http.HttpSession session,
              TagState _jsp_state)
    throws Throwable
  {
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.jsp.tagext.JspTag _jsp_parent_tag = null;
    com.caucho.jsp.PageContextImpl _jsp_parentContext = pageContext;
    response.setContentType("text/html; charset=utf-8");
    com.caucho.jsp.IteratorLoopSupportTag _jsp_loop_1 = null;

    out.write(_jsp_string0, 0, _jsp_string0.length);
    pageContext.requestSetOrRemove("base", "");
    out.write(_jsp_string1, 0, _jsp_string1.length);
    pageContext.sessionSetOrRemove("lang", "i18n/Page");
    out.write(_jsp_string1, 0, _jsp_string1.length);
    pageContext.sessionSetOrRemove("bundle", "i18n/Credit_card");
    out.write(_jsp_string2, 0, _jsp_string2.length);
    _caucho_expr_0.print(out, _jsp_env, false);
    out.write(_jsp_string3, 0, _jsp_string3.length);
    _caucho_expr_0.print(out, _jsp_env, false);
    out.write(_jsp_string4, 0, _jsp_string4.length);
    _caucho_expr_0.print(out, _jsp_env, false);
    out.write(_jsp_string5, 0, _jsp_string5.length);
    _caucho_expr_0.print(out, _jsp_env, false);
    out.write(_jsp_string6, 0, _jsp_string6.length);
    _caucho_expr_1.print(out, _jsp_env, false);
    out.write(_jsp_string7, 0, _jsp_string7.length);
    _jsp_loop_1 = _jsp_state.get_jsp_loop_1(pageContext, _jsp_parent_tag);
    java.lang.Object _jsp_items_2 = _caucho_expr_2.evalObject(_jsp_env);
    java.util.Iterator _jsp_iter_2 = com.caucho.jstl.rt.CoreForEachTag.getIterator(_jsp_items_2);
    _jsp_loop_1.init(0, Integer.MAX_VALUE, 1, false, false, false);
    while (_jsp_iter_2.hasNext()) {
      Object _jsp_i_2 = _jsp_iter_2.next();
      _jsp_loop_1.setCurrent(_jsp_i_2, _jsp_iter_2.hasNext());
      pageContext.setAttribute("map", _jsp_i_2);
      out.write(_jsp_string8, 0, _jsp_string8.length);
      _caucho_expr_3.print(out, _jsp_env, false);
      out.write(_jsp_string9, 0, _jsp_string9.length);
      _caucho_expr_4.print(out, _jsp_env, false);
      out.write(_jsp_string10, 0, _jsp_string10.length);
    }
    pageContext.pageSetOrRemove("map", null);
    out.write(_jsp_string11, 0, _jsp_string11.length);
  }

  private com.caucho.make.DependencyContainer _caucho_depends
    = new com.caucho.make.DependencyContainer();

  public java.util.ArrayList<com.caucho.vfs.Dependency> _caucho_getDependList()
  {
    return _caucho_depends.getDependencies();
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    _caucho_depends.add(depend);
  }

  protected void _caucho_setNeverModified(boolean isNotModified)
  {
    _caucho_isNotModified = true;
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;

    if (_caucho_isNotModified)
      return false;

    if (com.caucho.server.util.CauchoSystem.getVersionId() != 7031370602740370491L)
      return true;

    return _caucho_depends.isModified();
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
    TagState tagState;
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("WEB-INF/v4/redirect.jsp"), 6964972430589479368L, false);
    _caucho_depends.add(depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("common/tags.jsp"), -3608291857756734149L, false);
    _caucho_depends.add(depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("common/style.jsp"), -8516269833883808472L, false);
    _caucho_depends.add(depend);
  }

  static {
    try {
    } catch (Exception e) {
      e.printStackTrace();
      throw new RuntimeException(e);
    }
  }

  final static class TagState {
    private com.caucho.jsp.IteratorLoopSupportTag _jsp_loop_1;

    final com.caucho.jsp.IteratorLoopSupportTag get_jsp_loop_1(PageContext pageContext, javax.servlet.jsp.tagext.JspTag _jsp_parent_tag) throws Throwable
    {
      if (_jsp_loop_1 == null) {
        _jsp_loop_1 = new com.caucho.jsp.IteratorLoopSupportTag();
        _jsp_loop_1.setParent((javax.servlet.jsp.tagext.Tag) null);
      }

      return _jsp_loop_1;
    }

    void release()
    {
    }
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void caucho_init(ServletConfig config)
  {
    try {
      com.caucho.server.webapp.WebApp webApp
        = (com.caucho.server.webapp.WebApp) config.getServletContext();
      init(config);
      if (com.caucho.jsp.JspManager.getCheckInterval() >= 0)
        _caucho_depends.setCheckInterval(com.caucho.jsp.JspManager.getCheckInterval());
      _jsp_pageManager = webApp.getJspApplicationContext().getPageManager();
      com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
      manager.addTaglibFunctions(_jsp_functionMap, "spring", "http://www.springframework.org/tags");
      manager.addTaglibFunctions(_jsp_functionMap, "c", "http://java.sun.com/jstl/core");
      manager.addTaglibFunctions(_jsp_functionMap, "fmt", "http://java.sun.com/jstl/fmt");
      manager.addTaglibFunctions(_jsp_functionMap, "fn", "http://java.sun.com/jsp/jstl/functions");
      com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.InitPageContextImpl(webApp, this);
      _caucho_expr_0 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${base}");
      _caucho_expr_1 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${PaRes.action}");
      _caucho_expr_2 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${PaRes}");
      _caucho_expr_3 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${map.key}");
      _caucho_expr_4 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${map.value}");
    } catch (Exception e) {
      throw com.caucho.config.ConfigException.create(e);
    }
  }
  private static com.caucho.el.Expr _caucho_expr_0;
  private static com.caucho.el.Expr _caucho_expr_1;
  private static com.caucho.el.Expr _caucho_expr_2;
  private static com.caucho.el.Expr _caucho_expr_3;
  private static com.caucho.el.Expr _caucho_expr_4;

  private final static char []_jsp_string10;
  private final static char []_jsp_string8;
  private final static char []_jsp_string11;
  private final static char []_jsp_string7;
  private final static char []_jsp_string2;
  private final static char []_jsp_string3;
  private final static char []_jsp_string9;
  private final static char []_jsp_string6;
  private final static char []_jsp_string5;
  private final static char []_jsp_string0;
  private final static char []_jsp_string4;
  private final static char []_jsp_string1;
  static {
    _jsp_string10 = "\"/>\n    ".toCharArray();
    _jsp_string8 = "\n      <input type=hidden name=\"".toCharArray();
    _jsp_string11 = "\n  </form>\n  <script language=\"javascript\">\n    window.status=\"redirect to secure https site...\";\n    window.focus();\n  </script>\n</body>\n".toCharArray();
    _jsp_string7 = "\"\n      method=\"post\">\n\n    ".toCharArray();
    _jsp_string2 = "\n\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n<meta http-equiv=\"X-UA-Compatible\" content=\"IE=Edge\">\r\n<title></title> \r\n<link href=\"".toCharArray();
    _jsp_string3 = "/css/style.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n<link href=\"".toCharArray();
    _jsp_string9 = "\" value=\"".toCharArray();
    _jsp_string6 = "/css/payFor.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n\r\n<style type=\"text/css\">\r\n\r\n.table_ui thead th {\r\ncolor: #333;\r\npadding: 8px 10px;\r\nfont-size: 12px;\r\ntext-align: center;\r\nbackground: #f5f5f5;\r\nfont-weight: normal;\r\nborder: 1px solid #DBDBDB;\r\n}\r\n\r\n.table_ui  th {\r\ncolor: #333;\r\npadding: 8px 10px;\r\nfont-size: 12px;\r\ntext-align: center;\r\nbackground: #f5f5f5;\r\nfont-weight: normal;\r\nborder: 1px solid #DBDBDB;\r\n}\r\n\r\n.table_ui {\r\nborder-collapse: collapse;\r\nborder: 1px solid #DBDBDB;\r\nfont-family: Arial, Helvetica, sans-serif;\r\n}\r\n\r\n.table_ui td {\r\ntext-align: center;\r\npadding: 4px 10px;\r\nborder: 1px solid #DBDBDB;\r\nfont-size: 12px;\r\nline-height: 26px;\r\n}\r\n\r\n</style>\r\n\r\n<script language=\"javascript\" src=\"/js/jquery-1.7.js\"></script>\r\n<script language=\"javascript\" src=\"/js/jqstyle.js\"></script>\r\n</head>\r\n\r\n\r\n\n<body onload=\"PAForm.submit();\" oncontextmenu=\"return false\">\n  <form \n      name=\"PAForm\"\n      action=\"".toCharArray();
    _jsp_string5 = "/css/common.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n<link href=\"".toCharArray();
    _jsp_string0 = "\n\r\n\r\n\r\n\r\n\r\n".toCharArray();
    _jsp_string4 = "/css/cash.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n\r\n<link href=\"".toCharArray();
    _jsp_string1 = "\r\n".toCharArray();
  }
}
